# Generated by Django 4.0 on 2022-02-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('movie_name', models.CharField(max_length=30)),
                ('show_time', models.CharField(choices=[('Morning show', '10,0,0'), ('Afternoon show', '2,0,0'), ('Evening show', '6,0,0'), ('Night show', '10,0,0')], max_length=50)),
                ('theater', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
