# Generated by Django 4.0 on 2022-02-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showApp', '0002_show_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.CharField(choices=[('10,0,0', 'Morning show'), ('2,0,0', 'Afternoon show'), ('6,0,0', 'Evening show'), ('10,0,0', 'Night show')], max_length=50),
        ),
    ]
