# Generated by Django 4.0 on 2022-02-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showApp', '0003_alter_show_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(choices=[('10,0,0', 'Morning show'), ('14,0,0', 'Afternoon show'), ('18,0,0', 'Evening show'), ('22,0,0', 'Night show')]),
        ),
    ]
