# Generated by Django 4.0 on 2022-02-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showApp', '0005_alter_show_show_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='show_time',
            field=models.TimeField(choices=[('10 AM', 'Morning show'), ('2 PM', 'Afternoon show'), ('06 PM', 'Evening show'), ('10 PM', 'Night show')]),
        ),
    ]
